# Generated by Django 5.0.6 on 2024-06-02 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_todos_todoname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todos',
            name='todoName',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
