# Generated by Django 5.0.6 on 2024-06-03 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_todos_todoname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
